name: Release Package

on:
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.4.2
      with:
        github_token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
      env:
        GIT_COMMITTER_NAME: Semantic Release
        GIT_COMMITTER_EMAIL: action@github.com
